@api= http://localhost:3000/products

GET {{api}}
###

POST {{api}}
Content-Type: application/json
{
    "name": "computadora axus",
    "description": "pc gaming",
    "quantity": 45
}

### 
GET {{api}}/1

### 
DELETE  {{api}}/3

### 
GET {{api}}/count

### 
PUT {{api}}/1
Content-Type: application/json
{
    "name":"Laptop",
    "description":"Laptop hp",
    "quantity":"300"
}

